workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: '$CI_COMMIT_TAG !~ /^phabricator\//'

stages:
  - build

.build:
  stage: build
  image: docker.io/ubuntu:24.04
  script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get -y upgrade
    - DEBIAN_FRONTEND=noninteractive apt-get -y install cargo build-essential g++ libolm-dev libboost-json-dev wget cmake
    # catch2 is broken in ubuntu, see https://bugs.launchpad.net/ubuntu/+source/catch2/+bug/2081647
    - wget https://github.com/catchorg/Catch2/archive/v3.3.2.tar.gz -O catch2.tar.gz
    - tar -xf catch2.tar.gz
    - cd Catch2-*
    - mkdir build && cd build && \
    - cmake .. -DCATCH_ENABLE_WERROR=OFF -DBUILD_TESTING=OFF
    - make -j$(($(nproc) / 2)) install
    - cd ../..
    - rm -rf Catch2-* catch2.tar.gz
    - cd cpp
    - mv -v build.rs build.rs.orig
    - grep -v 'cargo::rerun-if-changed' build.rs.orig > build.rs
    - make BUILD_TYPE="$BUILD_TYPE" test

build:release:
  extends:
    - .build
  before_script:
    - BUILD_TYPE=release

build:debug:
  extends:
    - .build
  before_script:
    - BUILD_TYPE=debug
